# -*- coding: utf-8 -*-
"""TextAugmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D5G6XZEvSlW-5UpTGMqXNE4rbuHFpN-e
"""

from google.colab import drive
drive.mount('/content/gdrive/')

!pip install numpy requests nlpaug
!pip install transformers
!pip install torch

import numpy as np
import pandas as pd
# import nlpaug.augmenter.word as naw
import torch
import re
import random

df = pd.read_excel("/content/gdrive/MyDrive/프로젝트NLP/train_원본.xlsx")

pd.read_excel("/content/gdrive/MyDrive/프로젝트NLP/real_data.xlsx")

# RoBERTa 기반 증강기 설정 (substitute만 설정)
substitute_aug = naw.ContextualWordEmbsAug(
    model_path='roberta-base',
    action="substitute",
    device='cuda' if torch.cuda.is_available() else 'cpu'
)

# RoBERTa 기반 증강기 설정 (substitute만 설정)
substitute_aug = naw.ContextualWordEmbsAug(
    model_path='roberta-base',
    action="substitute",
    device='cuda' if torch.cuda.is_available() else 'cpu'
)

# 숫자를 제외한 텍스트 증강 함수
def augment_text(text):
    # 부호를 포함한 숫자를 추출하도록 정규식 수정
    numbers = re.findall(r'-?\d+\.?\d*', text)  # 음수를 포함한 숫자 찾기
    korean_chars = ['ㄱ', 'ㄴ', 'ㄷ', 'ㄹ', 'ㅁ', 'ㅂ', 'ㅅ', 'ㅇ', 'ㅈ', 'ㅊ']  # 한글 자음 사용
    number_placeholders = [korean_chars[i] for i in range(len(numbers))]  # 고유한 한글 자음으로 마스킹

    # 숫자를 고유한 한글 자음으로 치환
    for i, num in enumerate(numbers):
        text = text.replace(num, number_placeholders[i], 1)

    # 텍스트 증강 수행 (숫자가 없는 상태에서 substitute만 수행)
    augmented_text = substitute_aug.augment(text)

    # 리스트로 반환된 경우 문자열로 변환
    if isinstance(augmented_text, list):
        augmented_text = ' '.join(augmented_text)

    # 증강된 텍스트에서 고유한 한글 자음을 다시 원래 숫자로 복원
    for i, placeholder in enumerate(number_placeholders):
        if placeholder in augmented_text:
            augmented_text = augmented_text.replace(placeholder, numbers[i], 1)

    # 연속된 공백을 하나의 공백으로 변환
    augmented_text = re.sub(r'\s+', ' ', augmented_text).strip()

    return augmented_text

df['text_aug'] = df['text'].apply(lambda x: augment_text(x))

df[['text_aug','y']].to_excel("/content/gdrive/MyDrive/프로젝트NLP/train_aug.xlsx", index = False)