# -*- coding: utf-8 -*-
"""Backtranslation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p81gxsimlY6hjvohCWIUxVVteGzbqt5-
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install googletrans==4.0.0-rc1

from googletrans import Translator
import pandas as pd
import numpy as np

train_원본 = pd.read_excel('/content/drive/MyDrive/프로젝트NLP/train_원본.xlsx')

Back_aug = train_원본
translator = Translator()

# 'text' 컬럼의 모든 데이터에 대해 Back Translation 수행
augmented_texts = []
labels = []

for _, row in Back_aug.iterrows():
    text = row['text']
    label = row['y']
    try:
        # Step 1: 영어를 임의의 언어로 번역
        lang = random.choice(['fr', 'de', 'es', 'ko', 'ja'])  # 프랑스어, 독일어, 스페인어, 한국어, 일본어 중 랜덤 선택
        translated = translator.translate(text, src='en', dest=lang).text

        # Step 2: 다시 영어로 번역
        back_translated = translator.translate(translated, src=lang, dest='en').text

        # 증강된 텍스트와 원래 라벨을 리스트에 추가
        augmented_texts.append(back_translated)
        labels.append(label)
    except Exception as e:
        print(f"Translation error for text: {text}, error: {e}")
        continue

# 증강된 데이터프레임 생성
Back_aug_final = pd.DataFrame({'text': augmented_texts, 'y': labels})

Back_aug_final.to_excel('/content/drive/MyDrive/프로젝트NLP/train_backaug.xlsx', index=False)